/**
 * Autogenerated by Thrift Compiler (0.9.3)
 * <p>
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *
 * @generated
 */
package org.pyload.thrift;


public enum Output implements org.apache.thrift.TEnum {
    CAPTCHA(1),
    QUESTION(2),
    NOTIFICATION(4);

    private final int value;

    private Output(int value) {
        this.value = value;
    }

    /**
     * Get the integer value of this enum value, as defined in the Thrift IDL.
     */
    public int getValue() {
        return value;
    }

    /**
     * Find a the enum type by its integer value, as defined in the Thrift IDL.
     * @return null if the value is not found.
     */
    public static Output findByValue(int value) {
        switch (value) {
            case 1:
                return CAPTCHA;
            case 2:
                return QUESTION;
            case 4:
                return NOTIFICATION;
            default:
                return null;
        }
    }
}
